Bloc/rails-web-dev-example-collaboration-repo

README.md
I added a new name to the list of contributors
=> craig's version

README.md
Adding my name onto the list. Woot woot!
=> just dropping my name on the awesome list

README.md
adding me (Diane Kulseth) to the list!
=> add me to the list

README.md
=> Add my name!

README.md
added my name "mike liu" to the list!
=> added my name "mike liu"

README.md
Added my name after forking and cloning example code.  Next task, configure Git to sync fork.
=> Add Tish Snyder as collaborator

README.md
Add a new name to those listed in the README file
=> add name to README.md file

README.md~
=> Test Pull Request

README.md
=> Julia Commit 1

README.md
=> added my name to repository collaborators

README.md
For Github checkpoint on Full Stack Web Dev program - The assignment is to fork your repo, edit README.md, and initiate a pull request to merge changes.
=> Add name to list of repo collaborators

README.md
Adding my name to list, as per the bloc assignment on github lesson
=> Modified with my name

README.md
Hello,
I would like my name to be added to the list of famous people.
=> Adding my name (Jean-Denis Vauguet)

README.md
=> Update for Readme.md

README.md
=> test commit to fullstack example collabo

README.md
Requesting to add my name to the list
=> Added eric love

README.md
Added myself to complete GitHub checkpoint
=> Added Noel Deguzman to ReadMe.md

README.md
Adding my name to the README.md file.
=> Add "Wen Bo Xie"

README.md
Added my name "Alexandre Di Domenico" to the README.md
=> added my name to the README.md

README.md
Completing Bloc's GItHub assingment
=> added name Hugo Carlos to README

name.txt
=> Adding Dennis Le

README.md
=> commit vmanamino

README.md
=> Add David Yerger to list

README.md
=> Adding Cecily

README.md
=> Brock adding his name

README.md
Adding my name to the hall of fame.
=> Adding my name (Mike Keathley) to readme.md

README.md
Adding my name to README.md for bloc GitHub assignment
=> MY NAME ADDED

README.md
```
Adding my name to the list
```
=> Checkpoint Github

README.md
Saving my name to the list - em
=> trying to save my name

README.md
This is for my assignment to complete the Github checkpoint.
=> JOSEPH CAINTIC ADDED

README.md
Hi, hope I'm doing this right...
=> commit for Ross

README.md
My name is Junko Werner.  Please accept my pull request. Thank you.
=> add myname

README.md
Added Jeff D Rogers to README.md file
=> Added my name to list

README.md
=> Hello, please help!

README.md
Added my name, Tim Ryan, to the README.md file.
=> To add Tim Ryan to the README.md file

README.md
Added "Zayne Berndt" to the course work required in Full stack checkpoint 5.
=> Bloc checkpoint "Name Addition"

README.md
After almost a year I have added my name next to my mentor's, Mr. Ben Neely.
=> Chris Elwood

README.md
Completion of Bloc GitHub exercise:
-Created a fork of the repo
-Cloned to create a local copy of the repo
-Edited README.md to add myself as a contributor and committed changes
-Pushed commits from local to GitHub repo
-Initiated pull request
=> Added Dan Ruch to repo collaborators

README.md
=> Added Abhinay Tomar

README.md
=> Kevin O added changes

README.md
Added my name to the README.md.
=> Added Sanjay Patel to README.md

README.md
=> Name added to list

README.md
=> name added to README.md

README.md
=> Added name 'Jana Thalheim'
